default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

dev_test: &dev_test
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  port: 5432

development:
  <<: *dev_test
  database: rails_tutorial_6_development
test:
  <<: *dev_test
  database: rails_tutorial_6_test

production:
  <<: *default
  database: rails_tutorial_6_production
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
